### ISSUE TITLE
TypeError: option values must be strings

### ISSUE THREAD

**Issue by dipanjanMukherjee** [okomarov/dash_on_flask#6]
Hi,
when trying to run flask db migrate -m 'init' I get the following error

Traceback (most recent call last):
  File "C:\Users\Dipanjan\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Dipanjan\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dipanjan\Desktop\dash_on_flask-master\flaskenv\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\flask\cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\flask_migrate\cli.py", line 90, in migrate
    rev_id, x_arg)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\flask_migrate\__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\flask_migrate\__init__.py", line 215, in migrate
    version_path=version_path, rev_id=rev_id)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\alembic\command.py", line 197, in revision
    script_directory.run_env()
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\alembic\script\base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\alembic\util\pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\alembic\util\compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations\env.py", line 26, in <module>
    current_app.config.get('SQLALCHEMY_DATABASE_URI'))
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\alembic\config.py", line 237, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "c:\users\dipanjan\desktop\dash_on_flask-master\flaskenv\lib\site-packages\alembic\config.py", line 264, in set_section_option
    self.file_config.set(section, name, value)
  File "C:\Users\Dipanjan\Anaconda\lib\configparser.py", line 1192, in set
    self._validate_value_types(option=option, value=value)
  File "C:\Users\Dipanjan\Anaconda\lib\configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

I am using 'export DATABASE_URL=sqlite:///$PWD/app.db' in my .envrc.

**Comment by dipanjanMukherjee** [comment]
I resolved it. Anyone facing this issue on Windows can add the DATABASE_URL to environment variable and restart the machine, $PWD stands for present working directory where your local repository is kept. Thanks.
