### ISSUE TITLE
error initliaizing app db in the multi page branch example

### ISSUE THREAD

**Issue by glw** [okomarov/dash_on_flask#7]
After pip installs and setting up .envrc for dash multi page app. Im getting the error below.

```flask db init```
...
  ```
  File "/dash_on_flask/app/__init__.py", line 33
    url_base_pathname=f'/{base_pathname}/',
```

**Comment by okomarov** [comment]
Could you paste the full error message? That does not help much as I can’t reproduce the same behaviour.

**Comment by glw** [comment]
My apologies

Here's the info
Python version 3.5.2

The master (single page version) worked fine. When I switched over to the the multi-page version, I ran through the same steps as outlined in your blog post, and got this error.

```
Traceback (most recent call last):
  File "/home/garret/.virtualenvs/dash_on_flask/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/flask/cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/flask/cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/garret/.virtualenvs/dash_on_flask/lib/python3.5/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/dash_on_flask/app/__init__.py", line 33
    url_base_pathname=f'/{base_pathname}/',
                                         ^
SyntaxError: invalid syntax
```

Thanks!

**Comment by okomarov** [comment]
Are you using the https://github.com/okomarov/dash_on_flask/tree/feature/multiple_dash_apps branch?

Can you paste the contents of `__init__.py` because that looks like a syntax error which is happening somewhere else and it's not present under the multi app branch.

**Comment by glw** [comment]
yeah Im in that branch, heres is the directory for app/

app/
├── dashapp1
│   ├── callbacks.py
│   └── layout.py
├── dashapp2
│   ├── callbacks.py
│   └── layout.py
├── extensions.py
├── forms.py
├── __init__.py
├── models.py
├── templates
│   ├── base.html
│   ├── index.html
│   ├── login.html
│   └── register.html
└── webapp.py

Here is the contents of ```__init__.py```

```
import dash
from flask import Flask
from flask.helpers import get_root_path
from flask_login import login_required

from config import BaseConfig


def create_app():
    server = Flask(__name__)
    server.config.from_object(BaseConfig)

    from app.dashapp1.layout import layout as layout1
    from app.dashapp1.callbacks import register_callbacks as register_callbacks1
    register_dashapp(server, 'Dashapp 1', 'dashboard', layout1, register_callbacks1)

    from app.dashapp2.layout import layout as layout2
    from app.dashapp2.callbacks import register_callbacks as register_callbacks2
    register_dashapp(server, 'Dashapp 2', 'example', layout2, register_callbacks2)

    register_extensions(server)
    register_blueprints(server)

    return server


def register_dashapp(app, title, base_pathname, layout, register_callbacks_fun):
    # Meta tags for viewport responsiveness
    meta_viewport = {"name": "viewport", "content": "width=device-width, initial-scale=1, shrink-to-fit=no"}

    my_dashapp = dash.Dash(__name__,
                           server=app,
                           url_base_pathname=f'/{base_pathname}/',
                           assets_folder=get_root_path(__name__) + f'/{base_pathname}/assets/',
                           meta_tags=[meta_viewport])

    with app.app_context():
        my_dashapp.title = title
        my_dashapp.layout = layout
        register_callbacks_fun(my_dashapp)
    _protect_dashviews(my_dashapp)


def _protect_dashviews(dashapp):
    for view_func in dashapp.server.view_functions:
        if view_func.startswith(dashapp.url_base_pathname):
            dashapp.server.view_functions[view_func] = login_required(dashapp.server.view_functions[view_func])


def register_extensions(server):
    from app.extensions import db
    from app.extensions import login
    from app.extensions import migrate

    db.init_app(server)
    login.init_app(server)
    login.login_view = 'main.login'
    migrate.init_app(server, db)


def register_blueprints(server):
    from app.webapp import server_bp

    server.register_blueprint(server_bp)
```

**Comment by okomarov** [comment]
So, figured out the issue. It's the f-strings which are only availbale since python 3.6. Your version is from June 2016. 

So, there are two solutions:
* update python
* replace all occurences of f-strings with e.g. `str.format()` 

For the second option, for example:
```
url_base_pathname=f'/{base_pathname}/',
```
becomes
```
url_base_pathname='/{}/'.format(base_pathname),
```
[This](https://realpython.com/python-f-strings/#option-2-strformat) blog post has several examples of use cases.

**Comment by glw** [comment]
Ah I see. Ok, I suppose just to avoid other issues like this, I should give it a try in a more recent version. Thank you for the help!
